import type { GlobalCausalGraph } from "@/types/causal-graph";

/** Hardcoded prototype graph — replace with API when schema ships. */
export const CAUSAL_MAP_MOCK: GlobalCausalGraph = {
  activeEvents: 2,
  totalTheses: 4,
  lastUpdated: "2026-05-16T12:00:00.000Z",
  clusters: [
    {
      event: {
        id: "evt-war-deesc",
        slug: "war-de-escalation",
        title: "War risk",
        description: "Peace talks progress, oil risk fades, safe-haven bid unwinds",
        category: "geopolitics",
        confidence: 82,
        firstDetected: "2026-05-10T08:00:00.000Z",
        status: "active",
      },
      compositeMispricing: 74,
      conflictWarnings: [
        {
          thesisA: "Gold SHORT",
          thesisB: "Defense LONG",
          conflict:
            "Gold short and Defense long both stem from de-escalation — portfolio mixes safe-haven fade with risk-on defense bid; reconcile USD and rates exposure.",
        },
      ],
      theses: [
        {
          id: "th-gold-short",
          slug: "war-peace-gold-short",
          title: "Gold SHORT",
          statement: "Ceasefire path drains safe-haven premium from gold",
          targetAssetSymbol: "XAU",
          direction: "down",
          conviction: 79,
          mispricingScore: 79,
          timeHorizon: "2–8 weeks",
          affects: [
            {
              assetSymbol: "GLD",
              direction: "down",
              strength: 88,
              pricedInPercent: 72,
              mispricingScore: 42,
              whyItMatters: "ETF flows mirror spot — mostly priced",
              hasDedicatedThesis: false,
            },
            {
              assetSymbol: "IAU",
              direction: "down",
              strength: 72,
              pricedInPercent: 34,
              mispricingScore: 71,
              whyItMatters: "Lower-fee ETF lag — moderate edge",
              hasDedicatedThesis: false,
            },
            {
              assetSymbol: "GDX",
              direction: "down",
              strength: 65,
              pricedInPercent: 45,
              mispricingScore: 58,
              whyItMatters: "Miners lag spot on peace headlines",
              hasDedicatedThesis: false,
            },
            {
              assetSymbol: "UUP",
              direction: "down",
              strength: 48,
              pricedInPercent: 12,
              mispricingScore: 84,
              whyItMatters: "USD haven unwind underpriced vs gold fade",
              hasDedicatedThesis: false,
            },
          ],
        },
        {
          id: "th-defense-long",
          slug: "war-deesc-defense-long",
          title: "Defense LONG",
          statement: "Lower kinetic risk supports defense multiples vs gold",
          targetAssetSymbol: "ITA",
          direction: "up",
          conviction: 78,
          mispricingScore: 61,
          timeHorizon: "2–8 weeks",
          affects: [
            {
              assetSymbol: "LMT",
              direction: "up",
              strength: 70,
              pricedInPercent: 55,
              mispricingScore: 48,
              whyItMatters: "Prime contractor bid on budget clarity",
              hasDedicatedThesis: false,
            },
            {
              assetSymbol: "XLE",
              direction: "down",
              strength: 55,
              pricedInPercent: 38,
              mispricingScore: 62,
              whyItMatters: "Oil risk premium fades with ceasefire path",
              hasDedicatedThesis: false,
            },
          ],
        },
      ],
      impliedEffects: [
        {
          id: "imp-oil",
          assetSymbol: "CL / Brent",
          netDirection: "down",
          netStrength: 58,
          pricedInPercent: 52,
          fromTheses: ["Gold SHORT", "Defense LONG"],
          hasDedicatedThesis: false,
          whyItMatters: "Hormuz tail risk compresses — no dedicated oil thesis yet",
        },
        {
          id: "imp-dxy",
          assetSymbol: "DXY",
          netDirection: "down",
          netStrength: 44,
          pricedInPercent: 18,
          fromTheses: ["Gold SHORT"],
          hasDedicatedThesis: false,
          whyItMatters: "Haven USD unwind — overlaps UUP affect on gold thesis",
        },
        {
          id: "imp-fert",
          assetSymbol: "Fertilizer basket",
          netDirection: "up",
          netStrength: 22,
          pricedInPercent: 9,
          fromTheses: ["Defense LONG"],
          hasDedicatedThesis: false,
          whyItMatters: "Speculative third-order — input costs if supply chains normalize",
        },
      ],
    },
    {
      event: {
        id: "evt-fed-policy",
        slug: "fed-higher-for-longer",
        title: "Fed higher-for-longer",
        description: "Cuts pushed out; front-end yields sticky, duration pain persists",
        category: "monetary_policy",
        confidence: 76,
        firstDetected: "2026-05-08T14:00:00.000Z",
        status: "active",
      },
      compositeMispricing: 66,
      conflictWarnings: [],
      theses: [
        {
          id: "th-rates-short",
          slug: "fed-delay-cuts-rates-short",
          title: "Rates SHORT",
          statement: "Delayed cuts keep duration heavy — favor shorts on long bonds",
          targetAssetSymbol: "TLT",
          direction: "down",
          conviction: 78,
          mispricingScore: 69,
          timeHorizon: "2–8 weeks",
          affects: [
            {
              assetSymbol: "TLT",
              direction: "down",
              strength: 90,
              pricedInPercent: 67,
              mispricingScore: 38,
              whyItMatters: "Duration ETF — much of repricing done",
              hasDedicatedThesis: true,
              thesisSlug: "fed-delay-cuts-rates-short",
            },
            {
              assetSymbol: "HYG",
              direction: "down",
              strength: 52,
              pricedInPercent: 41,
              mispricingScore: 64,
              whyItMatters: "Credit spreads widen lagging rates move",
              hasDedicatedThesis: false,
            },
            {
              assetSymbol: "XLF",
              direction: "up",
              strength: 40,
              pricedInPercent: 28,
              mispricingScore: 55,
              whyItMatters: "Steepener helps banks if growth holds",
              hasDedicatedThesis: false,
            },
          ],
        },
      ],
      impliedEffects: [
        {
          id: "imp-credit",
          assetSymbol: "IG credit (LQD)",
          netDirection: "down",
          netStrength: 50,
          pricedInPercent: 35,
          fromTheses: ["Rates SHORT"],
          hasDedicatedThesis: false,
          whyItMatters: "Spread product — create thesis if funding stress builds",
        },
        {
          id: "imp-gold-rates",
          assetSymbol: "XAU",
          netDirection: "down",
          netStrength: 35,
          pricedInPercent: 58,
          fromTheses: ["Rates SHORT"],
          hasDedicatedThesis: true,
          thesisSlug: "war-peace-gold-short",
          whyItMatters: "Real yields headwind — watch overlap with geopolitics cluster",
        },
      ],
    },
    {
      event: {
        id: "evt-china-demand",
        slug: "china-stimulus-pulse",
        title: "China demand pulse",
        description: "Fiscal and credit lines inflect; industrial metals restocking narrative builds",
        category: "demand_shock",
        confidence: 71,
        firstDetected: "2026-05-12T06:00:00.000Z",
        status: "active",
      },
      compositeMispricing: 63,
      conflictWarnings: [],
      theses: [
        {
          id: "th-copper-long",
          slug: "china-stimulus-copper-long",
          title: "Copper LONG",
          statement: "Stimulus pulse shows up in copper before broad industrial basket",
          targetAssetSymbol: "HG",
          direction: "up",
          conviction: 75,
          mispricingScore: 63,
          timeHorizon: "2–8 weeks",
          affects: [
            {
              assetSymbol: "HG",
              direction: "up",
              strength: 92,
              pricedInPercent: 48,
              mispricingScore: 66,
              whyItMatters: "Primary expression — curve still behind spot demand",
              hasDedicatedThesis: true,
              thesisSlug: "china-stimulus-copper-long",
            },
            {
              assetSymbol: "FCX",
              direction: "up",
              strength: 78,
              pricedInPercent: 44,
              mispricingScore: 59,
              whyItMatters: "Equity beta to copper with operating leverage",
              hasDedicatedThesis: false,
            },
            {
              assetSymbol: "BHP",
              direction: "up",
              strength: 60,
              pricedInPercent: 86,
              mispricingScore: 18,
              whyItMatters: "Diversified miner — mostly priced in",
              hasDedicatedThesis: false,
            },
          ],
        },
      ],
      impliedEffects: [
        {
          id: "imp-iron",
          assetSymbol: "Iron ore",
          netDirection: "up",
          netStrength: 45,
          pricedInPercent: 32,
          fromTheses: ["Copper LONG"],
          hasDedicatedThesis: false,
          whyItMatters: "Second derivative on China build-out if copper confirms",
        },
      ],
    },
  ],
};
