/**
 * Structured per-instrument edge rows for shipped catalog theses (`ThesisAssetEdgeMap`).
 * Cascade prose stays macro-timeline; instrument-specific consensus/mispricing lives here.
 */
import type { RelatedAsset } from "./types";

const row = (r: RelatedAsset): RelatedAsset => r;

/** HG / COMEX only — never list COPPER as a separate card (alias duplicate). */
export const CHINA_STIMULUS_COPPER_RELATED_ASSETS: RelatedAsset[] = [
  row({
    symbol: "HG",
    note: "Primary futures expression",
    displayName: "HG (COMEX copper)",
    directionBias: "Constructive · long bias",
    whyItMatters:
      "Industrial-metals restock shows up in futures first; HG is the cleanest liquid expression of the China impulse without single-stock noise.",
    consensusOnAsset:
      "Open interest still anchors to weak PMI and property fear; desks treat stimulus headlines as untradeable until exports visibly rebound.",
    whatAssetMisprices:
      "Bonded inventory and credit impulse already trace a firmer restock path than Comex — HG is late, not early, if draws continue alongside credit confirmation.",
    edgeWindow: "Weeks to months (restock window)",
    depthConfidence: "Moderate — needs inventory + credit confirming together (see Trigger).",
  }),
  row({
    symbol: "FCX",
    note: "Copper miner",
    displayName: "FCX (Freeport-McMoRan)",
    directionBias: "Constructive · levered equity",
    whyItMatters: "Freeport is the most liquid large-cap read on spot copper; earnings move on realized price and volume, not just China headlines.",
    consensusOnAsset: "Equity still prices a mid-cycle margin squeeze and slow China — multiples lag spot when restock is real.",
    whatAssetMisprices:
      "FCX embeds slower volume growth than futures imply once bonded draws persist; equity revisions can lag HG by several weeks.",
    edgeWindow: "Weeks to quarters",
    depthConfidence: "Moderate-high — operating leverage amplifies both directions.",
  }),
  row({
    symbol: "SCCO",
    note: "Pure copper producer",
    displayName: "SCCO (Southern Copper)",
    directionBias: "Constructive · high-beta copper",
    whyItMatters: "Concentrated copper producer — second read when futures confirm but you want listed risk.",
    consensusOnAsset: "Flow treats SCCO as late-cycle commodity beta without separating restock from property stress.",
    whatAssetMisprices:
      "Peru supply noise masks China demand beta; if the impulse is real, SCCO’s beta to spot should exceed what single-name dispersion implies.",
    edgeWindow: "Weeks to months",
    depthConfidence: "Moderate — country and labor headlines add noise.",
  }),
  row({
    symbol: "TECK",
    note: "Diversified miner",
    displayName: "TECK (Teck Resources)",
    directionBias: "Watch · partial copper",
    whyItMatters: "Teck mixes met coal and copper — useful when the thesis broadens from red metal to industrial restock.",
    consensusOnAsset: "Investors bucket TECK with generic materials beta, not differentiated China restock exposure.",
    whatAssetMisprices:
      "Copper-linked cash flows are underweighted inside the conglomerate discount — restock broadening closes part of that gap.",
    edgeWindow: "Months",
    depthConfidence: "Lower than HG/FCX — copper is only part of the story.",
  }),
  row({
    symbol: "XME",
    note: "Metals & mining ETF",
    displayName: "XME (metals & mining)",
    directionBias: "Constructive · basket",
    whyItMatters: "Spreads the bet across miners — theme exposure without single-name event risk.",
    consensusOnAsset: "ETF flows chase a recession playbook; weights lean defensive versus a restock impulse.",
    whatAssetMisprices:
      "Basket pricing assumes broad margin pressure; a China-led metals bid can lift the complex before stock pickers split winners.",
    edgeWindow: "Months",
    depthConfidence: "Moderate — diversification dilutes edge vs HG.",
  }),
  row({
    symbol: "VALE",
    note: "Iron ore / steel-chain spillover",
    displayName: "VALE (iron ore lever)",
    directionBias: "Constructive watch",
    whyItMatters:
      "When restocking broadens beyond copper, iron ore and steel inputs often catch the second wave of the same China impulse.",
    consensusOnAsset: "Equity flow still treats VALE as bulk commodity beta without timing it to China credit windows.",
    whatAssetMisprices:
      "If bonded draws and credit stick but HG is extended, iron ore can still be late — the lag is the edge when the pulse is real.",
    edgeWindow: "Weeks to months",
    depthConfidence: "Moderate — not a pure copper read.",
  }),
  row({
    symbol: "TLT",
    note: "Duration hedge",
    displayName: "TLT (long Treasuries)",
    directionBias: "Defensive / contra watch",
    whyItMatters: "If China reflation sticks, it can delay Fed cuts — duration is the clean contra when industrial metals run hot.",
    consensusOnAsset: "Rates markets lean disinflation; China impulse is under-modeled in forward cuts.",
    whatAssetMisprices:
      "TLT may be too complacent if commodity-led growth nudges the Fed hawkish — watch curve vs metals leadership.",
    edgeWindow: "Months",
    depthConfidence: "Contextual — only if reflation prints broaden.",
  }),
  row({
    symbol: "UUP",
    note: "USD proxy",
    displayName: "UUP (USD index)",
    directionBias: "Watch · macro offset",
    whyItMatters: "Stimulus can strengthen or weaken USD via risk and funding — UUP is the stress tell alongside metals.",
    consensusOnAsset: "FX still trades simple risk-on/off; China impulse paths are more nuanced.",
    whatAssetMisprices:
      "A funding squeeze invalidates the metals leg faster than copper admits — UUP is the early warning.",
    edgeWindow: "Days to weeks when stress appears",
    depthConfidence: "Situational — align with Invalidation on USD spikes.",
  }),
];

const WAR_PEACE_GOLD: RelatedAsset[] = [
  row({
    symbol: "XAUUSD",
    displayName: "XAUUSD (spot gold)",
    note: "Hero / spot",
    directionBias: "Primary · fade war bid",
    whyItMatters: "Spot is where macro desks mark the war-risk premium; listed vehicles track it with lag and fees.",
    consensusOnAsset: "Spot still carries a wide tail-risk premium while engagement holds.",
    whatAssetMisprices:
      "Calm weeks and thinning escalation can leak premium before any treaty — spot can be slow versus headline diplomacy.",
    edgeWindow: "Days to weeks",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "GLD",
    displayName: "GLD (gold ETF)",
    note: "Listed gold",
    directionBias: "Primary · fade war bid",
    whyItMatters: "Where retail and funds warehouse the peace-fade — flows here lead spot on calm weeks.",
    consensusOnAsset: "Still pays a fat geopolitical tail; peace is assumed to be slow and reversible.",
    whatAssetMisprices:
      "ETF holdings embed more tail than engagement and escalation thinning imply — calm stacks before any treaty text.",
    edgeWindow: "Days to weeks",
    depthConfidence: "Moderate — flow data can lag spot.",
  }),
  row({
    symbol: "IAU",
    displayName: "IAU (gold ETF)",
    note: "Alternate vehicle",
    directionBias: "Constructive on gold · same theme",
    whyItMatters: "Sister vehicle to GLD — use for liquidity or borrow when GLD is crowded.",
    consensusOnAsset: "Treated interchangeably with GLD; few investors separate flow dynamics.",
    whatAssetMisprices: "Same war-premium wedge as GLD — no incremental edge vs GLD unless spreads gap.",
    edgeWindow: "Days to weeks",
    depthConfidence: "High correlation to GLD.",
  }),
  row({
    symbol: "GDX",
    displayName: "GDX (gold miners)",
    note: "Miners levered to spot",
    directionBias: "Watch · high beta",
    whyItMatters: "Miners amplify a falling gold path via costs and hedges — different default than bullion-only.",
    consensusOnAsset: "Equity screens still model flat real rates and sticky war risk into miner multiples.",
    whatAssetMisprices: "If bullion fear premium leaks, GDX operating leverage works both ways — equity can lead GLD lower.",
    edgeWindow: "Weeks",
    depthConfidence: "Moderate — equity noise adds beta.",
  }),
  row({
    symbol: "UUP",
    displayName: "UUP (USD)",
    note: "Contra / funding",
    directionBias: "Watch",
    whyItMatters: "Peace plus firm USD can accelerate gold unwinds — check dollar when fading safe havens.",
    consensusOnAsset: "FX often ignored in pure gold narratives.",
    whatAssetMisprices: "A dollar squeeze tightens financial conditions and keeps gold bid longer than spot fundamentals suggest.",
    edgeWindow: "Weeks",
    depthConfidence: "Contextual.",
  }),
  row({
    symbol: "TLT",
    displayName: "TLT (Treasuries)",
    note: "Rates / risk-off",
    directionBias: "Watch",
    whyItMatters: "Calm geopolitics can rotate into duration bids — TLT can compete with gold for safety flows.",
    consensusOnAsset: "Rates market may still price tail-risk overlap with gold.",
    whatAssetMisprices: "If peace stacks, some flows leave gold for bonds — cross-asset relief not in GLD price alone.",
    edgeWindow: "Weeks to months",
    depthConfidence: "Moderate.",
  }),
];

const HORMUZ_OIL: RelatedAsset[] = [
  row({
    symbol: "USOIL",
    displayName: "WTI-linked crude (futures / USO complex)",
    note: "Thesis asset",
    directionBias: "Constructive · jump risk",
    whyItMatters: "Primary expression for chokepoint repricing — gaps on routing and insurance news.",
    consensusOnAsset: "Flat crude vs hot freight — street treats strait headlines as noise until a verified print.",
    whatAssetMisprices: "Insurance and routing already embed higher chokepoint odds than flat price implies.",
    edgeWindow: "Weeks",
    depthConfidence: "High when freight confirms.",
  }),
  row({
    symbol: "BNO",
    displayName: "BNO (Brent)",
    note: "Brent leg",
    directionBias: "Constructive",
    whyItMatters: "Brent sets marginal barrels for many refiners — Hormuz hits Brent spreads first.",
    consensusOnAsset: "Retail focuses WTI headlines; Brent structure often leads the squeeze.",
    whatAssetMisprices: "Brent–WTI can widen on route risk before WTI catches — curve shape underweights chokepoint.",
    edgeWindow: "Weeks",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "XLE",
    displayName: "XLE (energy sector)",
    note: "Equity beta",
    directionBias: "Constructive",
    whyItMatters: "Energy equities catch sustained oil moves with lag — diversifies single-ETF oil risk.",
    consensusOnAsset: "Equity still discounts recurring capex and dividend policy vs spot volatility.",
    whatAssetMisprices: "Sector can re-rate after spot gaps if investors believe higher prices stick.",
    edgeWindow: "Weeks to months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "XOP",
    displayName: "XOP (E&P)",
    note: "Producers",
    directionBias: "Watch · high beta",
    whyItMatters: "E&Ps are levered to realized price — good if oil spike persists, painful if false alarm.",
    consensusOnAsset: "Models use strip prices that lag jump risk.",
    whatAssetMisprices: "OPEX and hedge books mean equities may not pay one-to-one with front crude on a spike.",
    edgeWindow: "Weeks",
    depthConfidence: "Moderate-low.",
  }),
  row({
    symbol: "TLT",
    displayName: "TLT",
    note: "Contra",
    directionBias: "Defensive watch",
    whyItMatters: "Oil shock plus growth fear can bid bonds — offsets if spike triggers risk-off.",
    consensusOnAsset: "Rates path often under-modeled in pure oil-long books.",
    whatAssetMisprices: "If kinetic risk fades fast, crude falls while duration catches a bid — book-level hedge.",
    edgeWindow: "Weeks",
    depthConfidence: "Contextual.",
  }),
];

const OPEC_UNITY: RelatedAsset[] = [
  row({
    symbol: "USOIL",
    displayName: "WTI-linked crude (futures / USO)",
    note: "Thesis asset",
    directionBias: "Constructive · grind",
    whyItMatters: "Primary liquid expression for slow-shale + OPEC discipline floor.",
    consensusOnAsset: "Market expects shale to add barrels; rig data says otherwise.",
    whatAssetMisprices:
      "Price still embeds easy spare capacity when cartel talk and rigs have both tightened — the floor is underpriced.",
    edgeWindow: "This quarter",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "XLE",
    displayName: "XLE",
    note: "Sector",
    directionBias: "Constructive",
    whyItMatters: "Integrateds and services capture higher-for-longer oil cash flows.",
    consensusOnAsset: "Sector multiples assume mid-cycle oil, not floor-building.",
    whatAssetMisprices: "Dividend and buyback capacity improves before spot mean-reverts — equity can lead.",
    edgeWindow: "Quarters",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "CVX",
    displayName: "CVX",
    note: "Major",
    directionBias: "Watch",
    whyItMatters: "Balance-sheet quality name if oil grinds — less beta than small-cap E&P.",
    consensusOnAsset: "Priced for oil mean reversion lower.",
    whatAssetMisprices: "If floor is real, majors re-rate on cash yield before strip fully agrees.",
    edgeWindow: "Quarters",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "XOM",
    displayName: "XOM",
    note: "Major",
    directionBias: "Watch",
    whyItMatters: "Similar to CVX — diversified production and downstream buffer.",
    consensusOnAsset: "Investors anchor to cyclical peak narratives.",
    whatAssetMisprices: "Underweights sustained cash generation if OPEC+US shale both tight.",
    edgeWindow: "Quarters",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "UNG",
    displayName: "UNG (natural gas)",
    note: "Related commodity",
    directionBias: "Watch",
    whyItMatters: "Gas sometimes correlates on energy sentiment — not core thesis but spillover read.",
    consensusOnAsset: "Often traded independently of oil rigs.",
    whatAssetMisprices: "Joint tightness in energy labor and services can lift both curves.",
    edgeWindow: "Months",
    depthConfidence: "Low linkage.",
  }),
];

const FED_TLT: RelatedAsset[] = [
  row({
    symbol: "TLT",
    displayName: "TLT",
    note: "Primary",
    directionBias: "Primary · short bias",
    whyItMatters: "Direct expression of delayed-cut repricing in long Treasuries.",
    consensusOnAsset: "Curve still leans dovish vs Fed dots.",
    whatAssetMisprices: "TLT carries an early-cut scenario while payrolls and CPI stay firm.",
    edgeWindow: "Data cycles",
    depthConfidence: "Moderate-high.",
  }),
  row({
    symbol: "IEF",
    displayName: "IEF (7–10y)",
    note: "Mid curve",
    directionBias: "Constructive short",
    whyItMatters: "Belly can move faster on first-cut repricing than long bond.",
    consensusOnAsset: "Often ignored vs TLT for retail.",
    whatAssetMisprices: "Belly may be less wrong than wings if cuts drift — relative value inside the short.",
    edgeWindow: "Weeks to months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "SHY",
    displayName: "SHY (short Treasury)",
    note: "Funding anchor",
    directionBias: "Watch",
    whyItMatters: "Front end anchors how painful higher-for-longer is for risk — check bill/2y when fading TLT.",
    consensusOnAsset: "Risk assets often under-model bill volatility.",
    whatAssetMisprices: "If cuts delay, front-end carry improves — competes with equity risk premium.",
    edgeWindow: "Months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "SPY",
    displayName: "SPY",
    note: "Risk proxy",
    directionBias: "Watch",
    whyItMatters: "Higher yields pressure multiples — SPY is the broad risk tell against your TLT view.",
    consensusOnAsset: "Equity still assumes soft landing.",
    whatAssetMisprices: "If yields rip on data, SPY can correct before bonds finish repricing.",
    edgeWindow: "Weeks",
    depthConfidence: "Contextual.",
  }),
  row({
    symbol: "GLD",
    displayName: "GLD",
    note: "Cross-asset",
    directionBias: "Watch",
    whyItMatters: "Real rates and risk-off can lift gold even as nominal yields rise — contra to pure TLT short.",
    consensusOnAsset: "Many rate models ignore gold as shadow duration hedge.",
    whatAssetMisprices: "If inflation surprises reappear, GLD can rally against your rates short.",
    edgeWindow: "Months",
    depthConfidence: "Situational.",
  }),
];

const DEFENSE_RTX: RelatedAsset[] = [
  row({
    symbol: "RTX",
    displayName: "RTX",
    note: "Hero",
    directionBias: "Primary · long",
    whyItMatters: "Named awards and backlog drive RTX rerate thesis.",
    consensusOnAsset: "Stock still prices program risk and political noise over booked work.",
    whatAssetMisprices: "Order book inflection not yet in forward margin assumptions.",
    edgeWindow: "Quarter",
    depthConfidence: "Moderate-high.",
  }),
  row({
    symbol: "LMT",
    displayName: "LMT",
    note: "Peer prime",
    directionBias: "Constructive",
    whyItMatters: "Shared appropriations cycle — LMT validates sector award cadence.",
    consensusOnAsset: "Peers sometimes diverge on execution quality.",
    whatAssetMisprices: "If RTX backlog rises, LMT often follows with lag — pair and spread opportunity.",
    edgeWindow: "Quarter",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "NOC",
    displayName: "NOC",
    note: "Peer",
    directionBias: "Watch",
    whyItMatters: "Aerospace + defense mix — read-through on classified and space budgets.",
    consensusOnAsset: "NOC trades idiosyncratic program headlines.",
    whatAssetMisprices: "Sector-wide budget lift can lift NOC even when RTX is the cleaner read.",
    edgeWindow: "Months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "ITA",
    displayName: "ITA (aerospace & defense ETF)",
    note: "Basket",
    directionBias: "Constructive",
    whyItMatters: "ETF for theme without single-program risk.",
    consensusOnAsset: "Flows lag primes on award news.",
    whatAssetMisprices: "Basket can re-rate on aggregate backlog before stock pickers split winners.",
    edgeWindow: "Months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "XAR",
    displayName: "XAR",
    note: "Defense ETF",
    directionBias: "Watch",
    whyItMatters: "Smaller-cap defense basket — higher beta to budget headlines.",
    consensusOnAsset: "Less liquid than ITA.",
    whatAssetMisprices: "If primes re-rate, XAR can overshoot on retail chase.",
    edgeWindow: "Weeks",
    depthConfidence: "Lower liquidity.",
  }),
  row({
    symbol: "TLT",
    displayName: "TLT",
    note: "Contra",
    directionBias: "Watch",
    whyItMatters: "Higher defense spend debates often meet fiscal hawks — duration can tighten funding.",
    consensusOnAsset: "Defense bull often ignores rates path.",
    whatAssetMisprices: "If issuance rises to fund budgets, TLT can sell off alongside RTX long.",
    edgeWindow: "Months",
    depthConfidence: "Contextual.",
  }),
];

const AI_QQQ: RelatedAsset[] = [
  row({
    symbol: "QQQ",
    displayName: "QQQ",
    note: "Hero",
    directionBias: "Primary · watch / underperform",
    whyItMatters: "Broad mega-cap basket hides margin dispersion from AI spend.",
    consensusOnAsset: "Index priced for smooth AI monetization.",
    whatAssetMisprices: "Several QQQ components can cut margin guide while index weights smooth the pain.",
    edgeWindow: "Two earnings seasons",
    depthConfidence: "Moderate — cluster trigger required.",
  }),
  row({
    symbol: "SMH",
    displayName: "SMH (semis)",
    note: "Upstream cost",
    directionBias: "Watch",
    whyItMatters: "Semis are the capex invoice many software names pay — leading indicator for margin squeeze.",
    consensusOnAsset: "SMH often trades growth narrative independent of customer P&L.",
    whatAssetMisprices: "If foundry pricing stays firm while cloud cuts spend, SMH vs QQQ spread matters.",
    edgeWindow: "Earnings windows",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "XLK",
    displayName: "XLK (tech sector)",
    note: "Sector",
    directionBias: "Watch",
    whyItMatters: "Broader tech weights dilute single-name margin cuts — benchmark for rotation.",
    consensusOnAsset: "Sector funds assume mean reversion in margins.",
    whatAssetMisprices: "If cuts cluster, XLK can lag quality factor even when headline tech is fine.",
    edgeWindow: "Months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "IWM",
    displayName: "IWM (small cap)",
    note: "Tell on credit",
    directionBias: "Watch",
    whyItMatters: "Smaller QQQ-adjacent names finance at IWM rates — credit stress shows here first.",
    consensusOnAsset: "Many investors ignore small-cap funding when trading mega-cap AI.",
    whatAssetMisprices: "Tighter credit hits high-capex small names before it hits MSFT-style balance sheets.",
    edgeWindow: "Months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "TLT",
    displayName: "TLT",
    note: "Contra",
    directionBias: "Watch",
    whyItMatters: "If AI spend slows growth, Fed can ease — duration bid competes with QQQ short thesis.",
    consensusOnAsset: "Growth vs rates path often modeled separately.",
    whatAssetMisprices: "Soft landing + easier Fed can lift QQQ against margin-fear narrative.",
    edgeWindow: "Quarters",
    depthConfidence: "Contextual.",
  }),
];

const EU_META: RelatedAsset[] = [
  row({
    symbol: "META",
    displayName: "META",
    note: "Hero",
    directionBias: "Primary · short",
    whyItMatters: "EU remedies hit ads and product surfaces META monetizes.",
    consensusOnAsset: "US flow treats fines as one-off, not structural revenue drag.",
    whatAssetMisprices: "Guidance still embeds old attach rates and ad load vs binding remedy text.",
    edgeWindow: "Remedy window",
    depthConfidence: "Moderate-high.",
  }),
  row({
    symbol: "GOOGL",
    displayName: "GOOGL",
    note: "Peer read-through",
    directionBias: "Watch",
    whyItMatters: "DMA-style rules create precedent across platforms — GOOGL is the clean comp.",
    consensusOnAsset: "Often trades as less exposed than META.",
    whatAssetMisprices: "If remedies tighten app and ad rules, GOOGL regulatory beta rises in sympathy.",
    edgeWindow: "Months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "XLK",
    displayName: "XLK",
    note: "Sector",
    directionBias: "Watch",
    whyItMatters: "Broad tech sentiment — META short vs XLK for relative expression.",
    consensusOnAsset: "Sector basket assumes diversified regulation risk.",
    whatAssetMisprices: "EU platform risk can concentrate in ad-heavy names inside XLK.",
    edgeWindow: "Months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "VGK",
    displayName: "VGK (Europe equities)",
    note: "Regional",
    directionBias: "Watch",
    whyItMatters: "Brussels enforcement tone shows up in European listings first.",
    consensusOnAsset: "US investors underweight local EU compliance costs.",
    whatAssetMisprices: "VGK can lag US mega-cap pain until fines convert to product change.",
    edgeWindow: "Months",
    depthConfidence: "Moderate.",
  }),
  row({
    symbol: "TLT",
    displayName: "TLT",
    note: "Macro",
    directionBias: "Watch",
    whyItMatters: "Regulation-driven margin drag can slow growth and bend Fed path — cross-check rates.",
    consensusOnAsset: "Often omitted in single-stock regulatory shorts.",
    whatAssetMisprices: "If EU slows growth, duration can rally while META still derates — book-level nuance.",
    edgeWindow: "Quarters",
    depthConfidence: "Low direct link.",
  }),
];

export const CATALOG_RELATED_ASSETS_BY_SLUG: Record<string, RelatedAsset[]> = {
  "china-stimulus-copper-long": CHINA_STIMULUS_COPPER_RELATED_ASSETS,
  "war-peace-gold-short": WAR_PEACE_GOLD,
  "strait-hormuz-oil-long": HORMUZ_OIL,
  "opec-unity-fracturing": OPEC_UNITY,
  "fed-pivot-delayed-tlt-weakness": FED_TLT,
  "us-defense-repricing-rtx-lmt": DEFENSE_RTX,
  "ai-capex-squeeze-qqq-rotation": AI_QQQ,
  "eu-tech-crackdown-megacap": EU_META,
};
